### ISSUE TITLE
SLM is crashing for unknown reason

### ISSUE THREAD

**Issue by huzbub** [RevoLand/Steam-Library-Manager#15] opened 2017-12-24 20:32 UTC
Way too much to put a single item into the topic heading.  Downloaded multiple versions including the most recent.  Struggled for some time before resorting to posting.

Tool sounds great!  Delivers nothing useful unless I'm doing something wrong.

Can't make a new library with the current GUI which does not match older screenshots and web pages promoting the tool.

Without the ability to make libraries you can't drag and drop to make a backup.  
![steammover1](https://user-images.githubusercontent.com/34818137/34329037-31a6b124-e8b7-11e7-87fc-045579a76d68.png)

**Comment by RevoLand** [comment] 2017-12-24 21:36
Hello,

First of all thank you for reaching out to me.

I'm very sorry about being unclear at the first place. To create libraries (Steam or SLM) you have to drop the folder you would like to use to the free space in the library panel. I will be updating the wiki soon.

Here is a gif demonstration: https://dl.dropboxusercontent.com/s/nap6qaw3tmix84k/25-Monday-VC092f5R510.gif

**Comment by huzbub** [comment] 2017-12-24 22:04
Thank you, that worked.  Doesn’t seem intuitive =|

 

My bad luck continues.  Crashes everytime I try to backup a game.

**Comment by RevoLand** [comment] 2017-12-24 22:07
I've just released an update (v1.4.4.3) fixing a crash releated to our acf reading method which used to crash SLM when the movement process gets to the end. Could you please try with the latest version, and if it still crashes could you please provide me more information if possible?

Thanks in advance and sorry to know that you are having issues with SLM!

**Comment by huzbub** [comment] 2017-12-24 22:09
Sure things, getting it now.  Though to my surprise clicking ‘yes’ seems to not do anything.  I will get it manually 😊

**Comment by huzbub** [comment] 2017-12-24 22:13
Still crashes at the end of the file copy with v1.4.4.3

 

Tried also with Run As Administrator just in case.

**Comment by huzbub** [comment] 2017-12-24 22:17
Tried copying a game from the C drive instead of the D drive, both to the E drive but this one did not crash!  

 



 

From: Alec Brown [mailto:huzbub@gmail.com] 
Sent: Sunday, December 24, 2017 4:14 PM
To: 'RevoLand/Steam-Library-Manager' <reply@reply.github.com>; 'RevoLand/Steam-Library-Manager' <Steam-Library-Manager@noreply.github.com>
Cc: 'Author' <author@noreply.github.com>
Subject: RE: [RevoLand/Steam-Library-Manager] Not working as intented (#15)

 

Still crashes at the end of the file copy with v1.4.4.3

 

Tried also with Run As Administrator just in case.

**Comment by RevoLand** [comment] 2017-12-24 22:19
Would you please test with this version?
https://send.firefox.com/download/a491209c6f/#90dTLqQA33e2p2svuYcIvg

**Comment by huzbub** [comment] 2017-12-24 22:24
Maybe it’s just that one game that causes issues (BattleZone).

 

Everything else so far is working without crashing.

**Comment by RevoLand** [comment] 2017-12-24 22:31
Would you please test with this one too?
https://send.firefox.com/download/a6cbc98343/#KYERh1cI1vS1JmSAsO5FNg

If it still crashes, i would like to get you in Steam, Skype, Discord or whatever you are using on your free time so we can debug it together. Thanks for your effort in this case, i really appreciate it! :)

**Comment by huzbub** [comment] 2017-12-24 22:36
Grabbing the new version and trying, found another game that crashes the tool.  Will report back.

**Comment by huzbub** [comment] 2017-12-24 23:16
Still crashes.  Recorded https://goo.gl/dpdLPr

**Comment by RevoLand** [comment] 2017-12-24 23:38
This one is supposed to log every unhandled exception to /Logs/SLM/<Start Date>.txt *(Note: You need to have Advanced Logger active)*

https://send.firefox.com/download/f96f757d43/#oNGd3GzSVyhQulRi_xSnyQ

Please let me know about the result/error if there is any. I really appreciate your help 👍

**Comment by huzbub** [comment] 2017-12-24 23:42
Attached entire logs folder.  Let me know if you don’t get it.

**Comment by RevoLand** [comment] 2017-12-24 23:44
You will have to link it or send it to my email (revoland@windowslive.com) as GitHub issues doesn't have supports for attachments

**Comment by huzbub** [comment] 2017-12-24 23:52
Sent to that email address.

**Comment by RevoLand** [comment] 2017-12-25 15:02
I'm still investigating the issue and trying to reproduce the bug. Will keep you updated.

**Comment by huzbub** [comment] 2017-12-25 16:11
I can help with testing later today, I need to wrap up a few things yet.

 

I don’t use skype, looks like I have discord but I haven't used it for quite a while, but I can likely figure it out.

**Comment by RevoLand** [comment] 2017-12-26 17:10
Hello again,

Can you please test with [latest version](https://github.com/RevoLand/Steam-Library-Manager/raw/master/Binaries/Steam%20Library%20Manager.exe) to see if it is still crashing for you?

**Comment by darkknight1812** [comment] 2017-12-30 07:12
I can confirm that SLM crashes towards the end of the copying process, even with the latest version. Let me know what you need from me.

**Comment by RevoLand** [comment] 2017-12-30 09:04
I am suspecting on file system watcher and would like to make a version without fswatcher to test if you don't mind testing. Your help is appreciated and will help future development of SLM :)

**Comment by darkknight1812** [comment] 2017-12-30 10:40
I do not mind testing. :)

**Comment by RevoLand** [comment] 2018-01-01 16:12
Hello again, i am sorry for the delay.

The version without FileSystemWatcher is ready to test now. Please keep me informed about the results.

https://send.firefox.com/download/30815a3eea/#5yrED5N3cmhV0Ne5hI2C9A

**Comment by darkknight1812** [comment] 2018-01-06 01:43
Sorry for the delay, but it seems to be working great now. Thanks.

**Comment by RevoLand** [comment] 2018-01-06 03:10
It is good to heard that. I'm closing the ticket now, please do not hesitate to contact me on any similar issue or feature requests etc.

Thanks again! :)

**Closed by RevoLand** 2018-01-06 03:10 UTC
Labels: bug, help wanted

**Comment by huzbub** [comment] 2018-01-06 03:43
Fantastic news, I will give it another try this weekend too!

**Comment by RevoLand** [comment] 2018-01-06 13:38
That would be great! Please keep me informed about the result so i can call this case off completely and start working on new stuff.
